#!/bin/bash

# DOCUMENT GENERATOR VAULT INSTALLER
# Installs the vault app and integrates with macOS

echo "🍎 Installing Document Generator Vault..."

# Get current directory
VAULT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_NAME="DocumentGeneratorVault"
APP_PATH="${VAULT_DIR}/${APP_NAME}.app"

echo "📍 Installation source: ${APP_PATH}"

# Check if app bundle exists
if [ ! -d "${APP_PATH}" ]; then
    echo "❌ App bundle not found at: ${APP_PATH}"
    echo "❌ Please make sure you're running this script from the correct directory"
    exit 1
fi

# Check for Node.js
if ! command -v node &> /dev/null; then
    echo "❌ Node.js not found. Please install Node.js first:"
    echo "   https://nodejs.org/en/download/"
    exit 1
fi

echo "✅ Node.js found: $(node --version)"

# Make executable permissions
echo "🔧 Setting executable permissions..."
chmod +x "${APP_PATH}/Contents/MacOS/${APP_NAME}"

# Copy app to Applications (optional)
read -p "📱 Install to Applications folder? (y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    if [ -d "/Applications/${APP_NAME}.app" ]; then
        echo "🗑️ Removing existing installation..."
        rm -rf "/Applications/${APP_NAME}.app"
    fi

    echo "📁 Copying app to Applications..."
    cp -R "${APP_PATH}" "/Applications/"
    
    if [ $? -eq 0 ]; then
        echo "✅ App installed to Applications folder"
        INSTALLED_PATH="/Applications/${APP_NAME}.app"
    else
        echo "⚠️ Failed to copy to Applications, using local installation"
        INSTALLED_PATH="${APP_PATH}"
    fi
else
    echo "📁 Using local installation"
    INSTALLED_PATH="${APP_PATH}"
fi

# Create command line alias
echo "🔗 Creating command line tools..."

# Create vault-cli command
sudo tee /usr/local/bin/vault-cli > /dev/null << EOF
#!/bin/bash
open "${INSTALLED_PATH}"
EOF

sudo chmod +x /usr/local/bin/vault-cli

# Create direct convergence commands
sudo tee /usr/local/bin/vault-converge > /dev/null << EOF
#!/bin/bash
cd "${VAULT_DIR}"
node convergence-engine.js converge
EOF

sudo chmod +x /usr/local/bin/vault-converge

echo "✅ Installation complete!"
echo ""
echo "🚀 Usage Options:"
echo ""
echo "   📱 GUI Application:"
if [[ $INSTALLED_PATH == "/Applications"* ]]; then
    echo "      • Open from Applications folder"
    echo "      • Spotlight search: '${APP_NAME}'"
fi
echo "      • Command: open '${INSTALLED_PATH}'"
echo "      • Alias: vault-cli"
echo ""
echo "   ⚡ Direct Commands:"
echo "      • vault-converge           # Run convergence directly"
echo "      • cd '${VAULT_DIR}' && npm run converge"
echo ""
echo "🧬 Character System Ready:"
echo "   💥 Ralph - Chaos coordination (70% in chaos mirror)"
echo "   🎯 Cal - Simplification specialist (70% in simple mirror)"
echo "   🎨 Arty - Design enhancement (20% aesthetic weight)"
echo "   🛡️ Charlie - Security protection (20% protection weight)"
echo ""
echo "🎯 Features Available:"
echo "   ⚡ Template convergence and deduplication"
echo "   💰 Template marketplace with buy/sell"
echo "   🗄️ File vault with versioning"
echo "   🌐 OSS network and ARD management"
echo "   📖 Automatic README/documentation generation"
echo ""
echo "🎉 Ready to use! Open the app and start converging your templates!"

# Optional: Generate initial README
echo ""
read -p "📝 Generate README for your vault? (y/n): " -n 1 -r
echo
if [[ $REPLY =~ ^[Yy]$ ]]; then
    echo "📝 Generating vault README..."
    
    cat > "${VAULT_DIR}/README-VAULT-QUICK-START.md" << 'EOF'
# 🏛️ Document Generator Vault - Quick Start

## 🎯 What This Is

Your unified vault for template convergence, character systems, and document processing.

### ⚡ Quick Actions

```bash
# Open the vault app
vault-cli

# Run convergence directly
vault-converge

# Scan for duplicates
npm run context-scan scan

# Mix character contexts  
npm run context-mix mix
```

### 🧬 Character System

- **💥 Ralph (Chaos)**: Real-time monitoring, bash operations, complex systems
- **🎯 Cal (Simple)**: Clean interfaces, external integration, optimization
- **🎨 Arty (Design)**: Aesthetic enhancement, creative solutions
- **🛡️ Charlie (Security)**: Protection, strategic deployment, reliability

### 💰 Economy Features

- Buy and sell templates in the marketplace
- $127 starting vault balance
- Templates: Convergence Engine ($15), Character System ($25), etc.

### 🔧 Integration

Your vault integrates with:
- Existing file systems and vaults
- OSS network and ARD management
- Economy and marketplace systems
- Documentation and storytelling tools

**Template layer confusion = SOLVED!** 🎉

Generated by Document Generator Vault Installer
EOF

    echo "✅ README created: README-VAULT-QUICK-START.md"
fi

echo ""
echo "🎊 Installation successful! Enjoy your unified document vault!"