#!/bin/bash

# ULTIMATE CHAOS SYSTEM LAUNCHER
# Multi-layer AI reasoning with chaos tunnels, secondary swarms, and data streaming overlay

clear

echo "🌀 LAUNCHING ULTIMATE AI CHAOS REASONING SYSTEM 🌀"
echo ""
echo "════════════════════════════════════════════════════════════════════════════════"
echo "  ⚡ INITIALIZING MULTI-LAYER REALITY..."
echo "  🌀 SPAWNING CHAOS TUNNELS..."
echo "  ✨ ACTIVATING SECONDARY AI SWARMS..."
echo "  📊 STREAMING XML/JSONL/YAML/MARKDOWN..."
echo "  🔍 ENABLING TRANSPARENT OVERLAY INTERFACE..."
echo "════════════════════════════════════════════════════════════════════════════════"
echo ""

# ASCII Chaos Art
echo "    🌀═══════════ CHAOS LAYER ARCHITECTURE ═══════════🌀"
echo ""
echo "    BASE LAYER:     💰 🏗️ ⚙️ 🎯  (Primary AI Builders)"
echo "    CHAOS LAYER:    🌀 🌀 🌀 🌀  (Instability Tunnels)"
echo "    SWARM LAYER:    ✨✨✨✨✨  (Secondary AI Clouds)"
echo "    DATA LAYER:     📊📄🔗📋  (Multi-Format Streams)"
echo "    OVERLAY LAYER:  🔍🎮🖱️💫  (Transparent Interface)"
echo ""
echo "    🌀═══════════════════════════════════════════════════🌀"
echo ""

# Start the AI reasoning backend
echo "📡 Starting AI Reasoning Backend Server..."
node RUNESCAPE-ECONOMY-XML-MAPPER.js &
BACKEND_PID=$!

# Wait for backend initialization
sleep 3

# Open the chaos system
echo "🌀 Opening Multi-Layer Chaos Interface..."
open CHAOS-TUNNEL-OVERLAY-SYSTEM.html

echo ""
echo "✅ ULTIMATE CHAOS SYSTEM ACTIVE!"
echo ""
echo "🎯 WHAT YOU'RE NOW EXPERIENCING:"
echo ""
echo "🏗️ BASE CIVILIZATION LAYER:"
echo "  • 4 Primary AI Builders (💰🏗️⚙️🎯) constructing civilization"
echo "  • Block-by-block construction with reasoning"
echo "  • Original Line Rider style physics and building"
echo ""
echo "🌀 CHAOS TUNNEL LAYER:"
echo "  • 5 Instability tunnels creating reality distortions"
echo "  • Entry/Exit/Nexus portals with pulsing energy"
echo "  • Tunnel surges that affect nearby AI builders"
echo "  • Reality glitch events that warp the entire system"
echo ""
echo "✨ SECONDARY AI SWARM LAYER:"
echo "  • 60+ secondary reasoning entities with 4 types:"
echo "    - 🟣 CHAOS: Erratic movement toward tunnels"
echo "    - 🟢 DATA: Smooth orbiting around primary AIs"
echo "    - 🟡 LOGIC: Grid-based methodical movement"
echo "    - 🔴 QUANTUM: Teleporting behavior"
echo ""
echo "📊 MULTI-FORMAT DATA STREAMING:"
echo "  • 📄 XML: Real-time AI state and system status"
echo "  • 🔗 JSONL: Streaming event logs with chaos metrics"
echo "  • 📋 YAML: Configuration and tunnel activity data"
echo "  • 📝 MARKDOWN: Event timeline with color coding"
echo ""
echo "🔍 TRANSPARENT OVERLAY INTERFACE:"
echo "  • Floating data panels that don't block interaction"
echo "  • Mouse probe showing detailed info about elements"
echo "  • Click-through overlay for seamless experience"
echo "  • Real-time position and chaos level tracking"
echo ""
echo "🎮 INTERACTION SYSTEMS:"
echo "  • Click primary AIs (💰🏗️⚙️🎯) to trigger chaos spikes"
echo "  • Watch swarms react to tunnel activity"
echo "  • See data streams update in real-time"
echo "  • Mouse probe reveals hidden system information"
echo ""
echo "🌀 CHAOS EVENTS YOU'LL SEE:"
echo "  • TUNNEL SURGE: Tunnels activate with energy bursts"
echo "  • SWARM CONVERGENCE: All chaos entities converge on point"
echo "  • AI CHAOS SPIKE: Primary AI gets corrupted temporarily"
echo "  • REALITY GLITCH: Entire system warps and distorts"
echo ""
echo "📊 DATA VISUALIZATION:"
echo "  • Each format has distinct color coding"
echo "  • Real-time chaos level percentages"
echo "  • Swarm density calculations around AIs"
echo "  • Tunnel proximity measurements"
echo "  • System stability metrics"
echo ""
echo "🎯 SECONDARY LANGUAGE FORMATS:"
echo "  • XML = System state (red text)"
echo "  • JSONL = Event streaming (cyan text)"
echo "  • YAML = Configuration (yellow text)"
echo "  • Markdown = Timeline (green text)"
echo ""
echo "🔍 FLOATING MOUSE PROBE SHOWS:"
echo "  • AI builders: Name and chaos percentage"
echo "  • Chaos tunnels: Instability zone warnings"
echo "  • AI swarms: Secondary logic type identification"
echo "  • Coordinates: Exact position data"
echo ""
echo "🌀 REASONING LAYERS:"
echo "  • Layer 1: Primary AI construction reasoning"
echo "  • Layer 2: Chaos tunnel instability logic"
echo "  • Layer 3: Secondary swarm collective intelligence"
echo "  • Layer 4: Data stream analysis and interpretation"
echo "  • Layer 5: Overlay interface meta-reasoning"
echo ""
echo "🎮 PRO TIPS:"
echo "  • Let it run for 2-3 minutes to see full chaos emerge"
echo "  • Click different AIs rapidly to create chaos cascades"
echo "  • Watch how swarms react to tunnel activity"
echo "  • Monitor data streams for system-wide patterns"
echo "  • Use mouse probe to understand element relationships"
echo ""
echo "🚀 ADVANCED FEATURES ACTIVE:"
echo "  • Multi-threaded reasoning across 5 layers"
echo "  • Real-time data format conversion"
echo "  • Chaos physics engine with tunnel dynamics"
echo "  • Swarm intelligence with 4 behavior types"
echo "  • Transparent overlay with click-through capability"
echo ""
echo "Press Ctrl+C to shut down the chaos and return to reality..."

# Wait for user to stop the madness
wait $BACKEND_PID