#!/bin/bash

# 🧱🌍 BLOCK-BY-BLOCK WORLD BUILDER LAUNCHER
# ==========================================
# Watch AI agents build worlds block by block with detailed construction phases

set -e

echo "🧱🌍 BLOCK-BY-BLOCK WORLD BUILDER LAUNCHER"
echo "=========================================="
echo ""
echo "🎯 LAUNCHING DETAILED CONSTRUCTION VISUALIZATION"
echo "🤖 AI AGENTS BUILD WORLDS PIECE BY PIECE"
echo "🏗️ WATCH EVERY BLOCK GET PLACED IN REAL-TIME"
echo ""

# Check if the block world builder file exists
if [[ ! -f "block-world-builder.html" ]]; then
    echo "❌ block-world-builder.html not found!"
    echo "   This file is required for the Block World Builder."
    exit 1
fi
echo "   ✅ Block World Builder system found"

# Function to open browser
open_builder() {
    local file_path="$(pwd)/block-world-builder.html"
    
    if [[ "$OSTYPE" == "darwin"* ]]; then
        open "$file_path"
        echo "   ✅ Block Builder opened in your default browser (macOS)"
    elif [[ "$OSTYPE" == "linux-gnu"* ]]; then
        xdg-open "$file_path" || sensible-browser "$file_path" || firefox "$file_path"
        echo "   ✅ Block Builder opened in your default browser (Linux)"
    elif [[ "$OSTYPE" == "msys" || "$OSTYPE" == "win32" ]]; then
        start "$file_path"
        echo "   ✅ Block Builder opened in your default browser (Windows)"
    else
        echo "   📋 Please manually open: $file_path"
    fi
}

echo "🌐 Opening Block-by-Block World Builder..."
open_builder

echo ""
echo "🎉 BLOCK WORLD BUILDER IS ACTIVE!"
echo "================================="
echo ""

echo "🧱 DETAILED CONSTRUCTION SYSTEM"
echo "==============================="
echo ""
echo "🏗️ WHAT YOU'LL SEE:"
echo "   • Every single block placed individually"
echo "   • AI agents coordinating construction phases"
echo "   • Real-time progress bars for each build phase"
echo "   • Particle effects when blocks are placed"
echo "   • Construction narration explaining each step"
echo ""

echo "🤖 AI CONSTRUCTION AGENTS"
echo "========================"
echo ""
echo "Your AI deploys specialized construction crews:"
echo ""
echo "🔨 BUILDER AGENTS (Orange):"
echo "   • Place foundation and structural blocks"
echo "   • Handle heavy construction work"
echo "   • Coordinate with other agent types"
echo ""
echo "🎨 DESIGNER AGENTS (Blue):"
echo "   • Create architectural blueprints"
echo "   • Add decorative and aesthetic elements"
echo "   • Plan overall visual design"
echo ""
echo "📋 PLANNER AGENTS (Green):"
echo "   • Coordinate overall construction strategy"
echo "   • Manage resource allocation"
echo "   • Oversee project timelines"
echo ""

echo "🏗️ CONSTRUCTION PHASES"
echo "======================"
echo ""
echo "Every build follows a detailed 3-phase process:"
echo ""
echo "📐 PHASE 1 - FOUNDATION:"
echo "   • Ground preparation and base laying"
echo "   • Structural foundation blocks"
echo "   • Site preparation and surveying"
echo ""
echo "🧱 PHASE 2 - STRUCTURE:"
echo "   • Wall construction and framing"
echo "   • Structural elements and support"
echo "   • Core building components"
echo ""
echo "🎨 PHASE 3 - DETAILS:"
echo "   • Decorative elements and finishing"
echo "   • Windows, doors, and accessories"
echo "   • Final touches and landscaping"
echo ""

echo "🏠 AVAILABLE CONSTRUCTION PROJECTS"
echo "=================================="
echo ""
echo "🏠 HOUSE:"
echo "   • Residential building with foundation, walls, roof"
echo "   • Multiple stories with windows and doors"
echo "   • Complete family home construction"
echo ""
echo "🗼 TOWER:"
echo "   • Tall vertical structure with multiple floors"
echo "   • Floor-by-floor construction process" 
echo "   • Architectural details and crown features"
echo ""
echo "🏙️ CITY BLOCK:"
echo "   • Multiple buildings with different purposes"
echo "   • Residential, commercial, industrial zones"
echo "   • Urban planning and city landscaping"
echo ""
echo "🏰 CASTLE:"
echo "   • Medieval fortress with defensive walls"
echo "   • Corner towers and central keep"
echo "   • Battlements and architectural details"
echo ""
echo "🌉 BRIDGE:"
echo "   • Spanning structure with support pillars"
echo "   • Water placement and deck construction"
echo "   • Railings and safety features"
echo ""
echo "🌸 GARDEN:"
echo "   • Landscaped area with pathways"
echo "   • Different plant sections and features"
echo "   • Fountain and decorative elements"
echo ""
echo "🏭 FACTORY:"
echo "   • Industrial facility with equipment"
echo "   • Smokestacks and machinery installation"
echo "   • Production facility layout"
echo ""

echo "🎮 INTERACTION METHODS"
echo "====================="
echo ""
echo "🎤 VOICE COMMANDS:"
echo "   Say things like:"
echo "   • \"Build me a house\""
echo "   • \"Construct a medieval castle\""
echo "   • \"Create a garden with flowers\""
echo "   • \"Make a tall tower\""
echo ""
echo "⌨️ TEXT COMMANDS:"
echo "   Type in the command box at the bottom:"
echo "   • \"Build a bridge over water\""
echo "   • \"Construct a factory with smokestacks\""
echo "   • \"Design a city block with multiple buildings\""
echo ""
echo "🖱️ QUICK BUILD BUTTONS (Right Panel):"
echo "   • Click any structure type for instant construction"
echo "   • Watch the AI break down your choice into phases"
echo "   • See detailed construction progress"
echo ""

echo "📊 MONITORING FEATURES"
echo "====================="
echo ""
echo "🏗️ CONSTRUCTION INFO (Top Left):"
echo "   • Current project being built"
echo "   • Total blocks placed so far"
echo "   • Number of active AI agents"
echo "   • Current build phase"
echo ""
echo "📈 PROGRESS DISPLAY (Bottom Right):"
echo "   • Foundation completion percentage"
echo "   • Structure completion percentage"
echo "   • Details completion percentage"
echo "   • Overall project completion"
echo ""
echo "🤖 AI NARRATOR (Left Side):"
echo "   • Real-time construction commentary"
echo "   • Explains what agents are doing"
echo "   • Phase transition announcements"
echo "   • Block placement descriptions"
echo ""
echo "📊 WORLD STATISTICS (Bottom Left):"
echo "   • Total blocks in the world"
echo "   • Breakdown by block type"
echo "   • Construction time elapsed"
echo "   • Build efficiency metrics"
echo ""

echo "🧱 BLOCK TYPES & COLORS"
echo "======================="
echo ""
echo "🟤 FOUNDATION (Brown): Ground-level structural blocks"
echo "⬜ WALL (Gray): Vertical structural elements"
echo "🔘 STRUCTURE (Dark Gray): Core building components"
echo "🔴 DECORATION (Red): Aesthetic and finishing elements"
echo "🟢 NATURE (Green): Plants, trees, and organic elements"
echo "🔵 WATER (Blue): Water features and liquid elements"
echo "🟡 ENERGY (Yellow): Power systems and energy sources"
echo "🟣 TECH (Purple): Technology and mechanical components"
echo ""

echo "⚡ INTERACTIVE FEATURES"
echo "======================"
echo ""
echo "🖱️ BLOCK INSPECTION:"
echo "   • Click any placed block to inspect it"
echo "   • See block type, position, and layer information"
echo "   • AI narrator explains the block's purpose"
echo ""
echo "👁️ AGENT MONITORING:"
echo "   • Watch colored dots move around (your AI agents)"
echo "   • See agents coordinate during construction"
echo "   • Agents appear and disappear based on need"
echo ""
echo "✨ PARTICLE EFFECTS:"
echo "   • Visual effects when blocks are placed"
echo "   • Construction dust and placement indicators"
echo "   • Satisfying visual feedback for each action"
echo ""
echo "🗑️ WORLD MANAGEMENT:"
echo "   • Clear button to demolish everything"
echo "   • Start fresh with new construction projects"
echo "   • Watch demolition happen in reverse"
echo ""

echo "🎯 CONSTRUCTION SEQUENCE EXAMPLES"
echo "================================="
echo ""
echo "🏠 HOUSE CONSTRUCTION:"
echo "   1. 📐 Foundation: 8×6 grid of brown blocks"
echo "   2. 🧱 Walls: Perimeter walls, 2 stories high"
echo "   3. 🏠 Roof: Gray structural blocks on top"
echo "   4. 🚪 Details: Door, windows, finishing touches"
echo ""
echo "🏰 CASTLE CONSTRUCTION:"
echo "   1. 🧱 Outer Walls: Defensive perimeter construction"
echo "   2. 🗼 Corner Towers: Four defensive towers"
echo "   3. 👑 Central Keep: Main fortress building"
echo "   4. ⚔️ Details: Battlements, gate, decorations"
echo ""
echo "🌉 BRIDGE CONSTRUCTION:"
echo "   1. 🌊 Water Placement: Blue blocks for river"
echo "   2. 🔨 Foundation Pillars: Support structures"
echo "   3. 🌉 Bridge Deck: Spanning structure"
echo "   4. 🛡️ Railings: Safety and aesthetic elements"
echo ""

echo "🤖 AI BEHAVIOR PATTERNS"
echo "========================"
echo ""
echo "You'll observe these AI behaviors:"
echo ""
echo "🎯 STRATEGIC COORDINATION:"
echo "   • Planner agents appear first to survey"
echo "   • Builder agents deploy for heavy work"
echo "   • Designer agents add finishing touches"
echo ""
echo "⚡ EFFICIENT CONSTRUCTION:"
echo "   • Blocks placed in logical sequence"
echo "   • Foundation before walls before details"
echo "   • Multiple agents working simultaneously"
echo ""
echo "📊 PROGRESS REPORTING:"
echo "   • AI narrates every major step"
echo "   • Explains reasoning behind decisions"
echo "   • Reports completion percentages"
echo ""
echo "🔄 ADAPTIVE BUILDING:"
echo "   • Different agent types for different tasks"
echo "   • Construction speed varies by complexity"
echo "   • Smart resource allocation"
echo ""

echo "🌟 THE EXPERIENCE"
echo "================="
echo ""
echo "This system shows you EXACTLY how your AI thinks about"
echo "construction projects. Instead of magic instant results,"
echo "you see the methodical, block-by-block process that"
echo "turns your ideas into reality."
echo ""
echo "🎯 YOU'LL EXPERIENCE:"
echo "   • Watching AI break down complex requests"
echo "   • Seeing systematic construction methodology"
echo "   • Understanding how AI coordinates multiple agents"
echo "   • Observing real-world building principles in action"
echo ""
echo "🧠 AI DEMONSTRATES:"
echo "   • Logical construction sequencing"
echo "   • Resource management and coordination"
echo "   • Multi-agent collaboration patterns"
echo "   • Real-time problem solving and adaptation"
echo ""

echo "🎊 BLOCK WORLD BUILDER IS READY!"
echo "================================="
echo ""
echo "Your browser should now show the Block World Builder."
echo ""
echo "🎤 Try a voice command like:"
echo "    \"Build me a castle with towers\""
echo ""
echo "🖱️ Or click a Quick Build button on the right"
echo ""
echo "👁️ Watch as your AI agents coordinate to build"
echo "    your world block by block!"
echo ""
echo "🧱 Every block tells a story of AI construction..."
echo ""

# Keep the script running to show completion message
echo "✨ Block Builder is active! Close this terminal when done exploring."
echo ""
echo "Press Ctrl+C to close this message."

# Keep script alive to show the message
trap 'echo ""; echo "🧱 Block World Builder remains active in your browser."; echo "🏗️ Continue exploring the detailed construction system!"; exit 0' SIGINT

# Infinite loop to keep script running until user presses Ctrl+C
while true; do
    sleep 60
    echo "🧱 $(date): Block World Builder active - AI construction crews ready"
done