#!/bin/bash
# Auto-generated by symlink-schema-autobash-validator.js
# Validates API keys across all layers

echo "🔑 API Key Validation Auto-Bash"
echo "==============================="

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# Check key status file
if [ -f ".key-status.json" ]; then
    echo -e "\n${GREEN}✓ Key status file found${NC}"
    
    # Count real vs placeholder keys
    REAL_KEYS=$(grep -c "canMakeAPICalls" .key-status.json || echo "0")
    PLACEHOLDER_KEYS=$(grep -c "reason" .key-status.json || echo "0")
    
    echo -e "\n📊 Key Statistics:"
    echo -e "  ${GREEN}Real Keys: $REAL_KEYS${NC}"
    echo -e "  ${YELLOW}Placeholder Keys: $PLACEHOLDER_KEYS${NC}"
    
    # Check critical services
    echo -e "\n🔍 Checking Critical Services:"
    
    # Stripe
    if grep -q "STRIPE.*canMakeAPICalls" .key-status.json; then
        echo -e "  ${GREEN}✓ Stripe: Real key detected${NC}"
    else
        echo -e "  ${RED}✗ Stripe: Using placeholder key${NC}"
    fi
    
    # OpenAI
    if grep -q "OPENAI.*canMakeAPICalls" .key-status.json; then
        echo -e "  ${GREEN}✓ OpenAI: Real key detected${NC}"
    else
        echo -e "  ${YELLOW}⚠ OpenAI: Using placeholder key${NC}"
    fi
    
    # Anthropic
    if grep -q "ANTHROPIC.*canMakeAPICalls" .key-status.json; then
        echo -e "  ${GREEN}✓ Anthropic: Real key detected${NC}"
    else
        echo -e "  ${YELLOW}⚠ Anthropic: Using placeholder key${NC}"
    fi
    
else
    echo -e "${RED}✗ Key status file not found${NC}"
    echo "Run: node symlink-schema-autobash-validator.js"
fi

# Check if services should make API calls
echo -e "\n🚦 API Call Permissions:"
if [ "$PLACEHOLDER_KEYS" -gt 0 ]; then
    echo -e "  ${YELLOW}⚠ WARNING: Some services using placeholder keys${NC}"
    echo -e "  ${YELLOW}  API calls to those services will be blocked${NC}"
else
    echo -e "  ${GREEN}✓ All keys validated - API calls enabled${NC}"
fi

# Export validation status
export KEY_VALIDATION_STATUS="checked"
export HAS_REAL_KEYS=$(($REAL_KEYS > 0 ? 1 : 0))
export HAS_PLACEHOLDER_KEYS=$(($PLACEHOLDER_KEYS > 0 ? 1 : 0))

echo -e "\n✅ Validation complete"