version: 2
updates:
  # Backend dependencies
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "finishthisidea-team"
    assignees:
      - "finishthisidea-team"
    labels:
      - "dependencies"
      - "backend"
    commit-message:
      prefix: "⬆️"
      include: "scope"
    versioning-strategy: "increase"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for critical dependencies
      - dependency-name: "prisma"
        update-types: ["version-update:semver-major"]
      - dependency-name: "@prisma/client"
        update-types: ["version-update:semver-major"]
      - dependency-name: "express"
        update-types: ["version-update:semver-major"]
    groups:
      prisma:
        patterns:
          - "prisma"
          - "@prisma/*"
      express-ecosystem:
        patterns:
          - "express"
          - "express-*"
      testing:
        patterns:
          - "jest"
          - "@types/jest"
          - "supertest"
          - "@types/supertest"
          - "vitest"
      linting:
        patterns:
          - "eslint"
          - "eslint-*"
          - "@typescript-eslint/*"
          - "prettier"

  # Frontend dependencies
  - package-ecosystem: "npm"
    directory: "/frontend"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 10
    reviewers:
      - "finishthisidea-team"
    assignees:
      - "finishthisidea-team"
    labels:
      - "dependencies"
      - "frontend"
    commit-message:
      prefix: "⬆️"
      include: "scope"
    versioning-strategy: "increase"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for React and core dependencies
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react-dom"
        update-types: ["version-update:semver-major"]
      - dependency-name: "vite"
        update-types: ["version-update:semver-major"]
    groups:
      react:
        patterns:
          - "react"
          - "react-*"
          - "@types/react"
          - "@types/react-*"
      vite:
        patterns:
          - "vite"
          - "vite-*"
          - "@vitejs/*"
      testing:
        patterns:
          - "vitest"
          - "@testing-library/*"
          - "jsdom"
      ui-libraries:
        patterns:
          - "lucide-react"
          - "framer-motion"
          - "tailwindcss"
          - "@tailwindcss/*"
      build-tools:
        patterns:
          - "typescript"
          - "@types/*"
          - "eslint"
          - "eslint-*"
          - "prettier"

  # Docker dependencies
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "09:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "finishthisidea-team"
    assignees:
      - "finishthisidea-team"
    labels:
      - "dependencies"
      - "docker"
    commit-message:
      prefix: "🐳"
      include: "scope"

  # GitHub Actions dependencies
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "UTC"
    open-pull-requests-limit: 5
    reviewers:
      - "finishthisidea-team"
    assignees:
      - "finishthisidea-team"
    labels:
      - "dependencies"
      - "github-actions"
    commit-message:
      prefix: "🔧"
      include: "scope"
    groups:
      actions:
        patterns:
          - "actions/*"
        exclude-patterns:
          - "actions/checkout"  # Keep this separate for stability
      docker-actions:
        patterns:
          - "docker/*"
      security-actions:
        patterns:
          - "github/codeql-action/*"
          - "aquasecurity/*"
          - "snyk/*"